language: csharp
os: linux
dist: trusty
sudo: required
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: none
dotnet: 2.0.0
script:
  - dotnet restore src/PackageReferenceEditor
  - dotnet build src/PackageReferenceEditor/PackageReferenceEditor.csproj -c Release -f netstandard2.0
  - dotnet restore src/PackageReferenceEditor.Avalonia
  - dotnet build src/PackageReferenceEditor.Avalonia/PackageReferenceEditor.Avalonia.csproj -c Release -f netcoreapp2.0
