version: '{build}'
image: Visual Studio 2017
configuration: Release
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- cmd: nuget.exe restore PackageReferenceEditor.sln
build:
  project: PackageReferenceEditor.sln
  verbosity: minimal
after_build:
- cmd: >-
    dotnet restore src/PackageReferenceEditor

    dotnet build src/PackageReferenceEditor/PackageReferenceEditor.csproj -c Release -f netstandard2.0

    dotnet pack src/PackageReferenceEditor/PackageReferenceEditor.csproj -c Release
test: off
artifacts:
- path: src\PackageReferenceEditor.WPF\bin\Release
  name: PackageReferenceEditor.WPF
- path: src\PackageReferenceEditor\bin\Release\*.nupkg
deploy: off
