version: '{build}'
image: Visual Studio 2017
configuration: Release
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- cmd: nuget.exe restore PackageReferenceEditor.sln
build:
  project: PackageReferenceEditor.sln
  verbosity: minimal
after_build:
- cmd: >-
    dotnet restore src/PackageReferenceEditor

    dotnet build src/PackageReferenceEditor/PackageReferenceEditor.csproj -c Release -f netstandard2.0

    dotnet pack src/PackageReferenceEditor/PackageReferenceEditor.csproj -c Release

    dotnet restore src/PackageReferenceEditor.Avalonia

    dotnet build src/PackageReferenceEditor.Avalonia/PackageReferenceEditor.Avalonia.csproj -c Release -f netcoreapp2.0

    dotnet publish src/PackageReferenceEditor.Avalonia/PackageReferenceEditor.Avalonia.csproj -c Release -f netcoreapp2.0 -r win7-x64 -o bin/win7-x64

    dotnet publish src/PackageReferenceEditor.Avalonia/PackageReferenceEditor.Avalonia.csproj -c Release -f netcoreapp2.0 -r ubuntu.14.04-x64 -o bin/ubuntu.14.04-x64

    dotnet publish src/PackageReferenceEditor.Avalonia/PackageReferenceEditor.Avalonia.csproj -c Release -f netcoreapp2.0 -r osx.10.12-x64 -o bin/osx.10.12-x64
test: off
artifacts:
- path: src\PackageReferenceEditor.Avalonia\bin\win7-x64
  name: PackageReferenceEditor.Avalonia-win7-x64
- path: src\PackageReferenceEditor.Avalonia\bin\ubuntu.14.04-x64
  name: PackageReferenceEditor.Avalonia-ubuntu.14.04-x64
- path: src\PackageReferenceEditor.Avalonia\bin\osx.10.12-x64
  name: PackageReferenceEditor.Avalonia-osx.10.12-x64
- path: src\PackageReferenceEditor.WPF\bin\Release
  name: PackageReferenceEditor.WPF
- path: src\PackageReferenceEditor\bin\Release\*.nupkg
deploy: off
