version: '{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- ps: .\build.ps1
test: off
deploy: off
artifacts:
- path: src\PackageReferenceEditor.Avalonia\bin\win7-x64
  name: PackageReferenceEditor.Avalonia-win7-x64
- path: src\PackageReferenceEditor.Avalonia\bin\ubuntu.14.04-x64
  name: PackageReferenceEditor.Avalonia-ubuntu.14.04-x64
- path: src\PackageReferenceEditor.Avalonia\bin\osx.10.12-x64
  name: PackageReferenceEditor.Avalonia-osx.10.12-x64
- path: src\PackageReferenceEditor\bin\Release\*.nupkg
