version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- cmd: nuget.exe restore MSBuildPropsUpdater\MSBuildPropsUpdater.sln
build:
  project: MSBuildPropsUpdater\MSBuildPropsUpdater.sln
  verbosity: minimal
test: off
artifacts:
- path: MSBuildPropsUpdater\MSBuildPropsUpdater\bin\Release
  name: MSBuildPropsUpdater
deploy: off
